apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
    - port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-np
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    nodePort: 30000
  type: NodePort

## access to url like below(Docker Desktop for Mac)
# ➜  kubernetes-dojo git:(main) ✗  kubectl get svc/nginx-np
# NAME       TYPE       CLUSTER-IP     EXTERNAL-IP   PORT(S)        AGE
# nginx-np   NodePort   10.100.52.22   <none>        80:30000/TCP   2m29s

### access to http://localhost:30000/

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-headless
spec:
  selector:
    app: nginx
  clusterIP: None