apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm
data:
  HOGEHOGE: FUGAFUGA
  config.txt: |
    hogehoge
    fugafuga
    foo bar baz

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bin-cm
binaryData:
  raw-urandom: VdTvKtYhKre+M05QtLm8laMKOyU=

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-data
data:
  HOGEHOGE: FUGAFUGA
  temp.txt: |
    hogehoge
    fugafuga
    foo bar baz
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-data
stringData:
  password: 1mbb1G968fb1CUg
  credential.txt: |
    credential data
    sWIEpx9wUdrVizVq
    UxuZ8kTeXvzyOWLQ
    7QVJIN1OI5FhxT9e